branches:
  only:
    - master

language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - SYMFONY_VERSION="4.2.*" DB=mysql

matrix:
  include:
    - php: 7.2

before_install:
  - composer self-update

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update
  - 'tests/testProject/bin/console p:m:m'

script:
  - bin/phpunit $PHPUNIT_FLAGS

services:
  - mysql
